### PR TITLE
More names!

### PR DESCRIPTION
**Pull request by darkdarcool**
I added a couple names to the list because the list was very short. So I took the liberty of making some new names!

Cheers!(btw I started saying that now)

### CODE REVIEW

**Comment by JBYT27** [comment]
Ooohh! Interesting!

**Comment by darkdarcool** [comment]
Will 100% add more names in the future

**Comment by darkdarcool** [comment]
thanks for the merge!

**Comment by JBYT27** [comment]
Lol np

**Comment by darkdarcool** [comment]
Can I have edit access so I can help a bit more, or should I just keep making pull requests?

**Comment by darkdarcool** [comment]
also im on replit

**Pull request merged**
